services:
  db:
    image: postgres
    env_file:
      - db.env
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    restart: always
  nextjs:
    build: ./
    env_file:
      - next.env
    restart: always
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
