networks:
  internal: {}
  proxy:
    external: true

services:
  db:
    image: postgres
    env_file:
      - db.env
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    restart: always
    networks:
      - internal
  nextjs:
    build: ./
    env_file:
      - next.env
    networks:
      - internal
      - proxy
